Repository kubernetes-sigs/etcdadm, pull requests merged in 2019-10, with the labels that each got.

#129 bugfix: FileMode should be octal expressed
  binary/etcd.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#136 test/e2e: init test
  test/e2e/init.sh
  test/e2e/utils.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#138 test/e2e: Run etcdadm in docker
  test/e2e/init.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#137 Add project roadmap
  README.md
  ROADMAP.md
Labels: approved, cncf-cla: yes, lgtm, size/S
