Repository kubernetes-sigs/etcdadm, pull requests merged in 2019-07, with the labels that each got.

#111 Add use cases doc
  docs/USECASES.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#110 include verification scripts for CI / PR verification
  apis/config.go
  binary/etcd.go
  certs/certs.go
  certs/pkiutil/pki_helpers.go
  certs/pkiutil/pki_helpers_test.go
  cmd/download.go
  cmd/info.go
  cmd/init.go
  cmd/join.go
  cmd/reset.go
  cmd/root.go
  cmd/version.go
  constants/constants.go
  docs/diagrams/init.md
  docs/diagrams/join.md
  docs/diagrams/reset.md
  etcd/etcd.go
  hack/update-all.sh
  hack/update-deps.sh
  hack/update-gofmt.sh
  hack/utils.sh
  hack/verify-all.sh
  hack/verify-boilerplate.go
  hack/verify-boilerplate.sh
  hack/verify-boilerplate_test.go
  hack/verify-build.sh
  hack/verify-deps.sh
  hack/verify-gofmt.sh
  hack/verify-golint.sh
  hack/verify-gotest.sh
  hack/verify-govet.sh
  hack/verify-shellcheck.sh
  hack/verify-spelling.sh
  hack/verify-whitespace.sh
  main.go
  pkg/logrus/logrus.go
  preflight/mandatory.go
  scripts/release.sh
  service/diff.go
  service/etcdctl.go
  service/systemd.go
  service/unit.go
  util/cmd.go
  util/filesystem.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, priority/important-longterm, size/XXL

#119 Add missing newline to end of USECASES.md
  docs/USECASES.md
Labels: approved, cncf-cla: yes, size/XS

#113 only download etcd archive if it does not exist
  binary/etcd.go
Labels: approved, cncf-cla: yes, lgtm, size/S
