Repository kubernetes-sigs/etcdadm, pull requests merged in 2019-03, with the labels that each got.

#91 Create OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/S

#92 Create SECURITY_CONTACTS
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/S

#93 Fix group name typos and clean up OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#95 cmd: print artifact download url
  cmd/init.go
  cmd/join.go
Labels: approved, cncf-cla: yes, size/S
