Repository kubernetes-sigs/etcdadm, pull requests merged in 2021-04, with the labels that each got.

#201 Fix staging build
  dev/staging/push.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#202 staging artifact upload: avoid double slash
  dev/staging/push.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#206 Add OWNERS file from kOps to etcd-manager
  etcd-manager/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/S

#207 Run tidy before vendoring modules
  etcd-manager/Makefile
  etcd-manager/go.mod
  etcd-manager/go.sum
  etcd-manager/vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#210 Set etcd server logger to "zap"
  etcd-manager/pkg/etcd/etcdprocess.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#211 Add "udev" to the etcd-manager image
  etcd-manager/images/base/BUILD
Labels: approved, cncf-cla: yes, lgtm, size/XS

#212 Perform file system resize on startup
  etcd-manager/pkg/volumes/mounter.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#213 Add packages required for systemd mounts
  etcd-manager/images/base/BUILD
Labels: approved, cncf-cla: yes, lgtm, size/S

#214 Makefile: Update go version from 1.12 to 1.16
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#216 OWNERS: Add etcd-manager owners to top-level owners
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#215 staging build: copy dist directory recursively
  dev/staging/push.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
