Repository kubernetes-sigs/etcdadm, pull requests merged in 2021-07, with the labels that each got.

#227 Don't restrict branches for GitHub Actions
  .github/workflows/main.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#228 Cleanup etcd-manager PKI code
  etcd-manager/cmd/etcd-manager/main.go
  etcd-manager/pkg/controller/controller.go
  etcd-manager/pkg/etcd/etcdprocess.go
  etcd-manager/pkg/etcd/etcdserver.go
  etcd-manager/pkg/etcd/pki.go
  etcd-manager/pkg/etcd/restore.go
  etcd-manager/pkg/pki/BUILD.bazel
  etcd-manager/pkg/pki/cas.go
  etcd-manager/pkg/pki/certs.go
  etcd-manager/pkg/pki/certutils.go
  etcd-manager/pkg/pki/fs.go
  etcd-manager/pkg/pki/fs_test.go
  etcd-manager/pkg/pki/store.go
  etcd-manager/pkg/tlsconfig/options.go
  etcd-manager/test/integration/harness/cluster.go
  etcd-manager/test/integration/harness/node.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#229 Add support for etcd 3.5.0
  constants/constants.go
  etcd-manager/WORKSPACE
  etcd-manager/images/BUILD
  etcd-manager/images/etcd.bzl
  etcd-manager/pkg/etcdversions/mappings.go
  etcd-manager/test/integration/BUILD.bazel
  etcd-manager/test/integration/clusterformation_test.go
  etcd-manager/test/integration/datapersists_test.go
  etcd-manager/test/integration/harness/cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#231 Update BUILD.bazel to include fs_test.go
  etcd-manager/pkg/pki/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/XS

#230 Support multiple CA certificates for key rotation
  etcd-manager/pkg/pki/cas.go
  etcd-manager/pkg/pki/certs.go
  etcd-manager/pkg/pki/certutils.go
  etcd-manager/pkg/pki/fs.go
  etcd-manager/pkg/pki/fs_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#235 Update semver and yaml modules
  etcd-manager/go.mod
  etcd-manager/go.sum
  etcd-manager/pkg/etcdversions/BUILD.bazel
  etcd-manager/pkg/etcdversions/mappings.go
  etcd-manager/pkg/legacy/BUILD.bazel
  etcd-manager/pkg/legacy/adopt.go
  etcd-manager/vendor/github.com/blang/semver/.travis.yml
  etcd-manager/vendor/github.com/blang/semver/README.md
  etcd-manager/vendor/github.com/blang/semver/package.json
  etcd-manager/vendor/github.com/blang/semver/v4/BUILD.bazel
  etcd-manager/vendor/github.com/blang/semver/v4/LICENSE
  etcd-manager/vendor/github.com/blang/semver/v4/go.mod
  etcd-manager/vendor/github.com/blang/semver/v4/json.go
  etcd-manager/vendor/github.com/blang/semver/v4/range.go
  etcd-manager/vendor/github.com/blang/semver/v4/semver.go
  etcd-manager/vendor/github.com/blang/semver/v4/sort.go
  etcd-manager/vendor/github.com/blang/semver/v4/sql.go
  etcd-manager/vendor/modules.txt
  etcd-manager/vendor/sigs.k8s.io/yaml/.gitignore
  etcd-manager/vendor/sigs.k8s.io/yaml/.travis.yml
  etcd-manager/vendor/sigs.k8s.io/yaml/BUILD.bazel
  etcd-manager/vendor/sigs.k8s.io/yaml/CONTRIBUTING.md
  etcd-manager/vendor/sigs.k8s.io/yaml/LICENSE
  etcd-manager/vendor/sigs.k8s.io/yaml/OWNERS
  etcd-manager/vendor/sigs.k8s.io/yaml/README.md
  etcd-manager/vendor/sigs.k8s.io/yaml/RELEASE.md
  etcd-manager/vendor/sigs.k8s.io/yaml/SECURITY_CONTACTS
  etcd-manager/vendor/sigs.k8s.io/yaml/code-of-conduct.md
  etcd-manager/vendor/sigs.k8s.io/yaml/fields.go
  etcd-manager/vendor/sigs.k8s.io/yaml/go.mod
  etcd-manager/vendor/sigs.k8s.io/yaml/go.sum
  etcd-manager/vendor/sigs.k8s.io/yaml/yaml.go
  etcd-manager/vendor/sigs.k8s.io/yaml/yaml_go110.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#205 Remove support for etcd v2
  etcd-manager/WORKSPACE
  etcd-manager/go.mod
  etcd-manager/go.sum
  etcd-manager/images/BUILD
  etcd-manager/pkg/backupcontroller/controller.go
  etcd-manager/pkg/controller/controller.go
  etcd-manager/pkg/controller/etcdclusterstate.go
  etcd-manager/pkg/controller/reconcile_configuration.go
  etcd-manager/pkg/controller/upgrade.go
  etcd-manager/pkg/etcd/backup.go
  etcd-manager/pkg/etcd/etcdprocess.go
  etcd-manager/pkg/etcdclient/BUILD.bazel
  etcd-manager/pkg/etcdclient/client.go
  etcd-manager/pkg/etcdclient/interfaces.go
  etcd-manager/pkg/etcdclient/localnode.go
  etcd-manager/pkg/etcdclient/member.go
  etcd-manager/pkg/etcdclient/v2.go
  etcd-manager/pkg/etcdversions/mappings.go
  etcd-manager/test/integration/BUILD.bazel
  etcd-manager/test/integration/harness/etcd.go
  etcd-manager/test/integration/harness/node.go
  etcd-manager/test/integration/upgradedowngrade/BUILD.bazel
  etcd-manager/vendor/go.etcd.io/etcd/client/pkg/v3/pathutil/BUILD.bazel
  etcd-manager/vendor/go.etcd.io/etcd/client/pkg/v3/pathutil/path.go
  etcd-manager/vendor/go.etcd.io/etcd/client/pkg/v3/srv/BUILD.bazel
  etcd-manager/vendor/go.etcd.io/etcd/client/pkg/v3/srv/srv.go
  etcd-manager/vendor/go.etcd.io/etcd/client/v2/BUILD.bazel
  etcd-manager/vendor/go.etcd.io/etcd/client/v2/LICENSE
  etcd-manager/vendor/go.etcd.io/etcd/client/v2/README.md
  etcd-manager/vendor/go.etcd.io/etcd/client/v2/auth_role.go
  etcd-manager/vendor/go.etcd.io/etcd/client/v2/auth_user.go
  etcd-manager/vendor/go.etcd.io/etcd/client/v2/cancelreq.go
  etcd-manager/vendor/go.etcd.io/etcd/client/v2/client.go
  etcd-manager/vendor/go.etcd.io/etcd/client/v2/cluster_error.go
  etcd-manager/vendor/go.etcd.io/etcd/client/v2/curl.go
  etcd-manager/vendor/go.etcd.io/etcd/client/v2/discover.go
  etcd-manager/vendor/go.etcd.io/etcd/client/v2/doc.go
  etcd-manager/vendor/go.etcd.io/etcd/client/v2/go.mod
  etcd-manager/vendor/go.etcd.io/etcd/client/v2/go.sum
  etcd-manager/vendor/go.etcd.io/etcd/client/v2/json.go
  etcd-manager/vendor/go.etcd.io/etcd/client/v2/keys.go
  etcd-manager/vendor/go.etcd.io/etcd/client/v2/members.go
  etcd-manager/vendor/go.etcd.io/etcd/client/v2/util.go
  etcd-manager/vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL
