Repository kubernetes-sigs/etcdadm, pull requests merged in 2021-11, with the labels that each got.

#248 Create test for backup and restore functionality
  .github/workflows/main.yml
  etcd-manager/WORKSPACE
  etcd-manager/test/integration/backuprestore/BUILD.bazel
  etcd-manager/test/integration/backuprestore/backuprestore_test.go
  etcd-manager/test/integration/harness/cluster.go
  etcd-manager/test/integration/harness/node.go
Labels: lgtm, size/L, cncf-cla: yes, approved

#253 etcd-manager - Allow all 3.X upgrades of one minor version
  etcd-manager/pkg/etcdversions/mappings.go
Labels: size/S, lgtm, cncf-cla: yes, approved

#252 Use unixs for "restore source" endpoint
  etcd-manager/pkg/etcd/etcdprocess.go
  etcd-manager/pkg/etcd/pki.go
  etcd-manager/pkg/etcd/restore.go
Labels: lgtm, size/L, cncf-cla: yes, approved

#254 Install bazelisk for bazel and bazelisk
  dev/staging/push.sh
Labels: lgtm, size/XS, cncf-cla: yes, approved

#255 Split staging builds for etcdadm and etcd-manager
  dev/staging/cloudbuild.yaml
  dev/staging/push-etcdadm.sh
  dev/staging/push-etcdmanager.sh
Labels: lgtm, size/M, cncf-cla: yes, approved

#256 Update Go to v1.17.3
  etcd-manager/WORKSPACE
Labels: lgtm, size/XS, cncf-cla: yes, approved

#258 Fix release of built assets for etcd-manager
  .github/workflows/main.yml
  dev/staging/push-etcdmanager.sh
  etcd-manager/dev/build-assets.sh
Labels: lgtm, size/M, cncf-cla: yes, approved

#259 staging builds: compute our own version
  dev/staging/cloudbuild.yaml
Labels: lgtm, size/XS, cncf-cla: yes, approved

#261 Replace etcd v3.5.0 with etcd v3.5.1
  constants/constants.go
  etcd-manager/WORKSPACE
  etcd-manager/go.mod
  etcd-manager/go.sum
  etcd-manager/images/BUILD
  etcd-manager/images/etcd.bzl
  etcd-manager/pkg/etcdversions/mappings.go
  etcd-manager/test/integration/BUILD.bazel
  etcd-manager/test/integration/backuprestore/BUILD.bazel
  etcd-manager/test/integration/clusterformation_test.go
  etcd-manager/test/integration/datapersists_test.go
  etcd-manager/test/integration/harness/cluster.go
  etcd-manager/test/integration/upgradedowngrade/BUILD.bazel
  etcd-manager/vendor/go.etcd.io/etcd/api/v3/version/version.go
  etcd-manager/vendor/go.etcd.io/etcd/client/v3/client.go
  etcd-manager/vendor/modules.txt
Labels: lgtm, size/L, cncf-cla: yes, approved

#262 Add unit test for env data generation
  apis/config.go
  go.mod
  go.sum
  service/env_test.go
  service/testdata/buildenvironment/simple/in.yaml
  service/testdata/buildenvironment/simple/want.txt
Labels: lgtm, size/L, cncf-cla: yes, approved

#264 hack/verify-all: highlight failed tests
  hack/verify-all.sh
Labels: lgtm, size/M, cncf-cla: yes, approved

#267 Fix .gitignore to not ignore vendoring
  etcd-manager/.gitignore
Labels: lgtm, size/XS, cncf-cla: yes, approved

#260 Release notes for etcd-manager v3.0.20211117
  etcd-manager/docs/releases/3.0.md
Labels: size/S, lgtm, cncf-cla: yes, approved
