Repository kubernetes-sigs/etcdadm, pull requests merged in 2021-03, with the labels that each got.

#187 etcd-manager/dev: move script interpreter to the first line
  etcd-manager/dev/add-symlink.sh
  etcd-manager/dev/build-assets.sh
  etcd-manager/dev/check-hashes.sh
  etcd-manager/dev/release.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#197 Use go.mod for verify-spelling
  etcd-manager/go.sum
  go.sum
  hack/tools/README.md
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  hack/verify-spelling.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#194 Build & stage etcd-manager also
  dev/staging/push.sh
  etcd-manager/dev/build-assets.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#195 Update with latest etcd-manager changes
  etcd-manager/dev/build-assets.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#199 Fix go module path for etcd-manager/tools/deb-tools
  etcd-manager/tools/deb-tools/go.mod
  etcd-manager/tools/deb-tools/vendor/github.com/go-logr/logr/BUILD.bazel
  etcd-manager/tools/deb-tools/vendor/k8s.io/klog/v2/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/XS

#200 Install bazel in staging build
  dev/staging/cloudbuild.yaml
  dev/staging/push.sh
Labels: approved, cncf-cla: yes, lgtm, size/S
