Repository kubernetes-sigs/etcdadm, pull requests merged in 2021-09, with the labels that each got.

#240 Run staticcheck using new versioned go-run syntax
  etcd-manager/Makefile
  etcd-manager/cmd/etcd-manager/tools.go
  etcd-manager/go.mod
  etcd-manager/go.sum
Labels: lgtm, size/M, cncf-cla: yes, approved

#239 Kubelet support improvements
  apis/config.go
  cmd/init.go
  cmd/join.go
  cmd/reset.go
  constants/constants.go
  go.mod
  initsystem/initsystem.go
  initsystem/kubelet/initsystem.go
  initsystem/systemd.go
  service/unit.go
Labels: ok-to-test, lgtm, cncf-cla: yes, size/XL, approved

#237 add custom bind addresss support to init
  apis/config.go
  cmd/init.go
  cmd/join.go
Labels: ok-to-test, lgtm, size/M, cncf-cla: yes, approved

#243 Remove configuration for creating GitHub releases via Travis CI
  .travis.yml
  scripts/release.sh
Labels: lgtm, size/M, cncf-cla: yes, approved
