Repository kubernetes-sigs/etcdadm, pull requests merged in 2022-07, with the labels that each got.

#323 Release etcd-manager/3.0.20220717
  etcd-manager/version.txt
Labels: lgtm, size/XS, cncf-cla: yes, approved

#324 Release notes for etcd-manager 3.0.20220717
  etcd-manager/docs/releases/3.0.md
Labels: lgtm, size/XS, cncf-cla: yes, approved

#327 updated retention period from 7 years to 2 for daily backups
  etcd-manager/pkg/backupcontroller/cleanup.go
Labels: ok-to-test, lgtm, size/XS, cncf-cla: yes, approved

#328 Fix reattachment of volumes for Hetzner
  etcd-manager/pkg/volumes/hetzner/volumes.go
Labels: lgtm, size/XS, cncf-cla: yes, approved

#329 Release etcd-manager/v3.0.20220727
  binary/etcd.go
  etcd-manager/version.txt
  hack/verify-gofmt.sh
Labels: lgtm, size/XS, cncf-cla: yes, approved

#330 Release notes for etcd-manager 3.0.20220727
  etcd-manager/docs/releases/3.0.md
Labels: lgtm, size/XS, cncf-cla: yes, approved

#332 Add makefile targets for building etcd-manager
  etcd-manager/Makefile
Labels: lgtm, size/XS, cncf-cla: yes, approved

#318 Add config drive as a source for OpenStack instance metadata
  etcd-manager/pkg/volumes/openstack/BUILD.bazel
  etcd-manager/pkg/volumes/openstack/testdata/metadata_drive.json
  etcd-manager/pkg/volumes/openstack/testdata/metadata_service.json
  etcd-manager/pkg/volumes/openstack/volumes.go
  etcd-manager/pkg/volumes/openstack/volumes_test.go
  etcd-manager/vendor/k8s.io/utils/exec/testing/BUILD.bazel
  etcd-manager/vendor/k8s.io/utils/exec/testing/fake_exec.go
  etcd-manager/vendor/modules.txt
Labels: ok-to-test, lgtm, cncf-cla: yes, size/XL, approved
