Repository kubernetes-sigs/etcdadm, pull requests merged in 2022-04, with the labels that each got.

#294 Document current release process for etcd-manager
  etcd-manager/.shipbot.yaml
  etcd-manager/docs/release-process.md
Labels: lgtm, size/L, cncf-cla: yes, approved

#303 etcd-manager - add support for etcd v3.5.3
  etcd-manager/WORKSPACE
  etcd-manager/go.mod
  etcd-manager/go.sum
  etcd-manager/images/BUILD
  etcd-manager/images/etcd.bzl
  etcd-manager/pkg/etcdversions/mappings.go
  etcd-manager/test/integration/BUILD.bazel
  etcd-manager/test/integration/backuprestore/BUILD.bazel
  etcd-manager/test/integration/upgradedowngrade/BUILD.bazel
  etcd-manager/vendor/github.com/prometheus/client_golang/prometheus/promhttp/BUILD.bazel
  etcd-manager/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  etcd-manager/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  etcd-manager/vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  etcd-manager/vendor/go.etcd.io/etcd/api/v3/v3rpc/rpctypes/error.go
  etcd-manager/vendor/go.etcd.io/etcd/api/v3/version/version.go
  etcd-manager/vendor/go.etcd.io/etcd/client/pkg/v3/logutil/zap.go
  etcd-manager/vendor/go.etcd.io/etcd/client/v3/client.go
  etcd-manager/vendor/go.etcd.io/etcd/client/v3/logger.go
  etcd-manager/vendor/go.etcd.io/etcd/client/v3/op.go
  etcd-manager/vendor/go.etcd.io/etcd/client/v3/retry_interceptor.go
  etcd-manager/vendor/go.etcd.io/etcd/client/v3/utils.go
  etcd-manager/vendor/modules.txt
Labels: lgtm, size/L, cncf-cla: yes, approved

#304 Set ETCD_EXPERIMENTAL_INITIAL_CORRUPT_CHECK for etcd 3.5.x
  etcd-manager/pkg/etcd/BUILD.bazel
  etcd-manager/pkg/etcd/etcdprocess.go
Labels: size/S, lgtm, cncf-cla: yes, approved

#305 Release notes for etcd-manager 3.0.20220417
  etcd-manager/docs/releases/3.0.md
Labels: lgtm, size/XS, cncf-cla: yes, approved

#306 docs: update release process for new name of promotion tool
  etcd-manager/docs/release-process.md
Labels: lgtm, size/XS, cncf-cla: yes, approved

#307 Sync klog versions / update to latest
  etcd-manager/go.mod
  etcd-manager/go.sum
  etcd-manager/vendor/github.com/go-logr/logr/README.md
  etcd-manager/vendor/github.com/go-logr/logr/logr.go
  etcd-manager/vendor/k8s.io/klog/v2/BUILD.bazel
  etcd-manager/vendor/k8s.io/klog/v2/OWNERS
  etcd-manager/vendor/k8s.io/klog/v2/README.md
  etcd-manager/vendor/k8s.io/klog/v2/contextual.go
  etcd-manager/vendor/k8s.io/klog/v2/exit.go
  etcd-manager/vendor/k8s.io/klog/v2/imports.go
  etcd-manager/vendor/k8s.io/klog/v2/internal/buffer/BUILD.bazel
  etcd-manager/vendor/k8s.io/klog/v2/internal/buffer/buffer.go
  etcd-manager/vendor/k8s.io/klog/v2/internal/clock/BUILD.bazel
  etcd-manager/vendor/k8s.io/klog/v2/internal/clock/README.md
  etcd-manager/vendor/k8s.io/klog/v2/internal/clock/clock.go
  etcd-manager/vendor/k8s.io/klog/v2/internal/serialize/BUILD.bazel
  etcd-manager/vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  etcd-manager/vendor/k8s.io/klog/v2/internal/severity/BUILD.bazel
  etcd-manager/vendor/k8s.io/klog/v2/internal/severity/severity.go
  etcd-manager/vendor/k8s.io/klog/v2/k8s_references.go
  etcd-manager/vendor/k8s.io/klog/v2/klog.go
  etcd-manager/vendor/k8s.io/klog/v2/klog_file.go
  etcd-manager/vendor/k8s.io/klog/v2/klog_file_others.go
  etcd-manager/vendor/k8s.io/klog/v2/klog_file_windows.go
  etcd-manager/vendor/k8s.io/klog/v2/klogr.go
  etcd-manager/vendor/modules.txt
  go.mod
  go.sum
  initsystem/kubelet/initsystem.go
Labels: lgtm, size/XXL, cncf-cla: yes, approved

#309 Add initial support for Hetzner Cloud
  etcd-manager/cmd/etcd-manager/BUILD.bazel
  etcd-manager/cmd/etcd-manager/main.go
  etcd-manager/go.mod
  etcd-manager/go.sum
  etcd-manager/pkg/volumes/hetzner/BUILD.bazel
  etcd-manager/pkg/volumes/hetzner/discovery.go
  etcd-manager/pkg/volumes/hetzner/volumes.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/LICENSE
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/BUILD.bazel
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/action.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/certificate.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/client.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/datacenter.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/error.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/firewall.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/floating_ip.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/hcloud.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/helper.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/image.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/internal/instrumentation/BUILD.bazel
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/internal/instrumentation/metrics.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/iso.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/load_balancer.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/load_balancer_type.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/location.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/metadata/BUILD.bazel
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/metadata/client.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/network.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/placement_group.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/pricing.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/rdns.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/resource.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/schema.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/BUILD.bazel
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/action.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/certificate.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/datacenter.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/error.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/firewall.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/floating_ip.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/image.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/iso.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/load_balancer.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/load_balancer_type.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/location.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/meta.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/network.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/placement_group.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/pricing.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/server.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/server_type.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/ssh_key.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/volume.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/server.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/server_type.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/ssh_key.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/testing.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/volume.go
  etcd-manager/vendor/modules.txt
Labels: lgtm, size/XXL, cncf-cla: yes, approved

#311 Update hcloud-go to v1.33.2
  etcd-manager/WORKSPACE
  etcd-manager/go.mod
  etcd-manager/go.sum
  etcd-manager/tools/deb-tools/WORKSPACE
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/BUILD.bazel
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/error.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/hcloud.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/labels.go
  etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/metadata/client.go
  etcd-manager/vendor/modules.txt
Labels: lgtm, size/M, cncf-cla: yes, approved

#312 Add support for etcd v3.5.4
  etcd-manager/WORKSPACE
  etcd-manager/go.mod
  etcd-manager/go.sum
  etcd-manager/images/BUILD
  etcd-manager/images/etcd.bzl
  etcd-manager/pkg/etcdversions/mappings.go
  etcd-manager/test/integration/BUILD.bazel
  etcd-manager/test/integration/backuprestore/BUILD.bazel
  etcd-manager/test/integration/upgradedowngrade/BUILD.bazel
  etcd-manager/vendor/go.etcd.io/etcd/api/v3/version/version.go
  etcd-manager/vendor/modules.txt
Labels: lgtm, size/M, cncf-cla: yes, approved
