Repository kubernetes-sigs/etcdadm, pull requests merged in 2022-02, with the labels that each got.

#291 Fix ipv6 detection
  etcd-manager/pkg/volumes/aws/discovery.go
  etcd-manager/pkg/volumes/aws/volumes.go
Labels: size/S, lgtm, cncf-cla: yes, approved

#292 Test for nil in to not found check
  etcd-manager/pkg/volumes/aws/volumes.go
Labels: lgtm, size/XS, cncf-cla: yes, approved

#293 Release notes for etcd-manager 3.0.20220203
  etcd-manager/docs/releases/3.0.md
Labels: size/S, lgtm, cncf-cla: yes, approved

#296 `make container-build` support GOPROXY env
  Makefile
  README.md
Labels: needs-ok-to-test, lgtm, size/XS, cncf-cla: yes, approved
