Repository kubernetes-sigs/etcdadm, pull requests merged in 2023-02, with the labels that each got.

#358 Add support for etcd v3.5.7
  etcd-manager/Makefile
  etcd-manager/WORKSPACE
  etcd-manager/go.mod
  etcd-manager/go.sum
  etcd-manager/images/BUILD
  etcd-manager/images/etcd.bzl
  etcd-manager/pkg/etcdversions/mappings.go
  etcd-manager/test/integration/BUILD.bazel
  etcd-manager/test/integration/backuprestore/BUILD.bazel
  etcd-manager/test/integration/backuprestore/backuprestore_test.go
  etcd-manager/test/integration/clusterformation_test.go
  etcd-manager/test/integration/datapersists_test.go
  etcd-manager/test/integration/harness/cluster.go
  etcd-manager/test/integration/resize_cluster_test.go
  etcd-manager/test/integration/upgradedowngrade/BUILD.bazel
  etcd-manager/vendor/go.etcd.io/etcd/api/v3/version/version.go
  etcd-manager/vendor/go.etcd.io/etcd/client/v3/watch.go
  etcd-manager/vendor/modules.txt
  etcd-manager/version.txt
Labels: lgtm, size/L, cncf-cla: yes, approved

#359 Update the release process for etcd-manager
  etcd-manager/docs/release-process.md
Labels: size/S, lgtm, cncf-cla: yes, approved

#356 Update etcdadm build
  .github/workflows/e2e.yml
  Makefile
  cmd/version.go
  constants/constants.go
  go.mod
  go.sum
  test/e2e/cluster.sh
  test/e2e/cluster_phases.sh
  test/e2e/init.sh
Labels: lgtm, cncf-cla: yes, size/XL, approved

#362 etcdadm: Should close GRPC clients
  cmd/info.go
  cmd/init.go
  cmd/join.go
  cmd/reset.go
  etcd/etcd.go
Labels: lgtm, size/XS, cncf-cla: yes, approved

#363 Use etcd 3.4 client
  .github/workflows/e2e.yml
  cmd/init.go
  cmd/join.go
  cmd/reset.go
  etcd/etcd.go
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/XL, approved

#361 Restart the server using the recommended etcd version
  etcd-manager/pkg/etcd/etcdserver.go
  etcd-manager/test/integration/resize_cluster_test.go
Labels: lgtm, size/M, cncf-cla: yes, approved

#365 Update to go 1.19.5
  etcd-manager/.bazelrc
  etcd-manager/.bazelversion
  etcd-manager/WORKSPACE
  etcd-manager/tools/deb-tools/.bazelrc
  etcd-manager/tools/deb-tools/WORKSPACE
Labels: lgtm, size/M, cncf-cla: yes, approved

#366 Use official Bazel container image with Cloud Build
  .github/workflows/main.yml
  Makefile
  dev/staging/cloudbuild.yaml
  dev/staging/push-etcdmanager.sh
  etcd-manager/cloudbuild-master.yaml
  etcd-manager/cloudbuild.yaml
Labels: lgtm, size/M, cncf-cla: yes, approved

#367 Add gsutil when using Cloud Build
  dev/staging/cloudbuild.yaml
  dev/staging/push-etcdadm.sh
Labels: size/S, lgtm, cncf-cla: yes, approved
