Repository kubernetes-sigs/etcdadm, pull requests merged in 2023-01, with the labels that each got.

#354 etcdadm: update to latest etcd client
  cmd/init.go
  cmd/join.go
  cmd/reset.go
  etcd/etcd.go
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/XL, approved

#355 Build slim etcd-manager image without etcd binaries
  etcd-manager/Makefile
  etcd-manager/cloudbuild-master.yaml
  etcd-manager/cloudbuild.yaml
  etcd-manager/images/BUILD
Labels: lgtm, size/M, cncf-cla: yes, approved

#357 Release etcd-manager/v3.0.20230119
  etcd-manager/version.txt
Labels: lgtm, size/XS, cncf-cla: yes, approved
